### ISSUE TITLE
Add documentation about how to choose a fixed port for mock server in consumer tests

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#119]
It might help in some cases to be able to set a fixed port for the mock server used when running consumer tests, this is already achievable by overriding `mockProviderConfig: MockProviderConfig` from `RequestResponsePactForgerResources` but not documented.

Example:
```scala
class MyTest ... with RequestResponsePactForger {

  override val mockProviderConfig: MockProviderConfig = MockProviderConfig.httpConfig("localhost", 9003)

  ...

}
```

**Comment by jbwheatley** [comment]
agreed, this is something that needs to be documented
