### ISSUE TITLE
ProviderState is missing params attribute

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#120]
The documentation and the actual content received by a provider states that a `ProviderState` is of the form `{"state" : "the provider state id string", "params": { "id": "bob" } }` but the definition of `ProviderState` case class is not up to date and only contains the `state`.

**Comment by gaeljw** [comment]
I'm not sure how to approach fixing this issue though.

Adding `params: Option[Map[String, Any]]` to the case class will mess with the JSON libraries as `Any` cannot be (de)serialized.

Should we create an abstraction for "types that are serializable" independant of Circe or other JSON library? :thinking:

**Comment by jbwheatley** [comment]
can you point to where that is in the docs? At a cursory glance I only found this https://docs.pact.io/implementation_guides/jvm/provider#provider-state

**Comment by gaeljw** [comment]
I was actually talking about pact4s documentation at https://github.com/jbwheatley/pact4s/blob/0bdd234d232d8a1359a44e0a849ffb6cdf1f0f00/README.md?plain=1#L272. It looks like official pact documentation is not up to date on this.

Though I can confirm that if some parameters are set on the provider state, they are received in the `params` attributes  in current implementation of pact4s on provider side.

**Comment by solarmosaic-kflorence** [comment]
Maybe we can start with `params: Map[String, String]` and perhaps accept a type `T` later?

**Comment by gaeljw** [comment]
> Maybe we can start with `params: Map[String, String]` and perhaps accept a type `Map[String, T]` later? Although technically you can put a JSON string as the value, so really `Map[String, String]` should work for almost every case.

You mean we parse everything into a `String`? `1` would become `"1"` and objects/arrays would become their JSON representation?

Why not as a 1st step :shrug:

**Comment by solarmosaic-kflorence** [comment]
@gaeljw the most common use case for `params` is just substituting dynamic pieces of the state. Previous to having `params` (which is somewhat new), we would have states like "Customer with ID [some_id] exists", whereas now it would be "Customer exists" with params `{"id":"[some_id]"}`. I have never practically seen a use-case that needs anything more complicated than a string value, and the solution for those cases is simple. Of course, using a JSON parser is more flexible, but it's also more complicated, and we would need a backup in case the user does not include one of the optional parsing libraries anyways.

**Comment by gaeljw** [comment]
I'm fine with that. I do see use case of getting a numeric value directly but as the provider needs to know how to use the parameter it will know how to transform the `String` if a transformation is needed anyway.

I'll provide a PR in coming days :)

**Comment by gaeljw** [comment]
I've opened #136 , any feedback is welcome ;)
