### ISSUE TITLE
Support V4 Pact specifications by default

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#124]
Upgrading to pact-jvm 4.3.x should be enough to make V4 the default.

**Comment by gaeljw** [comment]
The bump is not automatic as:
- pact-jvm 4.3.x brings Apache HTTP library in version 5
- pact-jvm 4.1.x still brings Apache HTTP library in version 4

This means that some shared code that references HTTP classes like `HttpRequest` will have to be moved and duplicated to the java8/java11 folder with appropriate import in each.

**Comment by gaeljw** [comment]
You know better than me the impacts of this but indeed it's a bit of a shame to duplicate code just because of this :)

**Comment by solarmosaic-kflorence** [comment]
@jbwheatley I support that decision. It will make it much easier for others to contribute to this project.

**Comment by solarmosaic-kflorence** [comment]
In fact we may want to maintain even incompatible Pact JVM versions in separate branches as well (e.g. `4.3.x` vs `4.1.x`) -- hopefully we won't need to backport too may fixes and encourage folks to try to stay on the latest version.

**Comment by jbwheatley** [comment]
Java 8 will always be 4.1.x, whereas java 11+ and 4.3.x+ will be our main target. So should only need the 2 branches

**Comment by solarmosaic-kflorence** [comment]
Ah, I meant `4.2.x` vs `4.3.x`, although I'm not sure if there are incompatibilities between them.

**Comment by jbwheatley** [comment]
released in v0.1.0
