### ISSUE TITLE
Got "writing pacts for ... to target/pacts" from logger but no such file found

### ISSUE THREAD

**Issue by tanyagorn** [jbwheatley/pact4s#178]
I'm using "io.github.jbwheatley" %% "pact4s-scalatest" % "0.1.0-java8"

During running test, I got this Info log 
[info] Pact4s-Logger - Writing pacts for consumer Consumer(name=FraudBackofficeAPI) and provider Provider(name=FraudMlAPI) to target/pacts

However there is no such file exist in target/pacts like log mentioned. Not in my target/pacts path, and not anywhere else. Seem like it's not generated. What's wrong here?

below is my code for my test class

```
class PactTest extends AsyncFunSuite with Matchers with RequestResponsePactForger with Mockito with MockWSHelpers {

  val clientId = 2

  override def pact: RequestResponsePact = ConsumerPactBuilder
    .consumer("FraudBackofficeAPI")
    .hasPactWith("FraudMlAPI")
    .uponReceiving("getAllNameNationalityProbability")
    .path("http://test:port/predict-nationality")
    .method("POST")
    .headers(
      Map(
        "Content-Type" -> "application/json",
        "ClientId" ->  clientId.toString,
        "RequestId" -> "123e4567-e89b-42d3-a456-556642440000"
      )
    )
    .body(
      """{"name":"John Doe",
        |"maxResult":3}
        |""".stripMargin,
      "application/json"
    )
    .willRespondWith()
    .status(200)
    .body("""{
            |  "ARE": 0.0015790796301290394,
            |  "ARG": 0.0015750796301290393,
            |  "AUS": 0.027795471251010895
            |}
            |""".stripMargin)
    .toPact


  test("getAllNameNationalityProbability should return response for any name") {

    val config = mock[FraudBackofficeConfig]
    when(config.fraudMlServerConfig)
      .thenReturn(FraudMlServerConfig(Seq("http://test:port"), 2))

    val ws = MockWS {
      case ("POST", "http://test:port/predict-nationality") =>
        Action {
          Ok(Json.obj(
            "ARE" -> 0.0015790796301290393,
            "ARG" -> 0.0015750796301290393,
            "AUS" -> 0.027795471251010895
          ))
        }
    }

    val fraudMlClient = new FraudMlServerClientImpl(config, ws)
    val getNameNat = fraudMlClient.getAllNameNationalityProbability("John Doe")
    assert(getNameNat != null)
  }

}
```

**Comment by jbwheatley** [comment]
Hi @tanyagorn, I've checked this on the latest java8 tag (0.2.0-java8) and the one you're one, and I can see the pact files being written in our tests. Is it being written to anywhere on your file system? Could you try explicitly setting the destination like we do here https://github.com/jbwheatley/pact4s/blob/080b233dbc3515ebb6a953781c18634e2dbd07aa/example/consumer/src/test/scala/http/consumer/ScalaTestPact.scala#L23 and see if that solves your issue

**Comment by jbwheatley** [comment]
you might also find it useful to enable debug logging for pact-jvm - `au.com.dius.pact` is the package you would want to enable

**Comment by tanyagorn** [comment]
Hi @jbwheatley, I've enable debug logging as you suggested. 

This is the result

![image](https://user-images.githubusercontent.com/19620433/159253442-dbe7a7ee-ef1b-4e8e-8b6e-3921ca694929.png)

There is still no pact file generated from my pact test. So, I try enable debug log in a project that pact test is working and this is the result. (it's different test in different project)

![image](https://user-images.githubusercontent.com/19620433/159254788-00f27518-a37c-4788-9ab9-4629bfe76201.png)

Comparison between logging from two projects that I've noticed.
1. After mock server is started, success pact run will have BaseJdkMockServer - Received request with POST method along with info.
2. Before mock server is shutdown, success pact run will have BaseMockServer write .json file to target/pacts directory
However, in the project that there is no pact file generated. The mock server is start and then shutdown without doing anything. 

Seem like there is no request sending to mock server. But I've already called the method though. Why?

**Comment by jbwheatley** [comment]
Ok, it seems that pact-jvm won't write the pact file unless the mock server has received requests for all of the defined interactions - so because the request is not being sent, the pact file is not being written

**Comment by jbwheatley** [comment]
it doesn't look like in your test class that the request is being sent to the mock server (sorry if it is and i'm just being blind). you can get the url by calling `mockSever.getUrl` from within the test class.

**Comment by jbwheatley** [comment]
sorry, I don't recognise what http client library you are using - if you could minimise an example with dependencies that recreates your issue, it will be easier for me to help debug 😺
