### ISSUE TITLE
Consider advising developers to use native provider

### ISSUE THREAD

**Issue by caoilte** [jbwheatley/pact4s#24]
I'm evaluating this as an alternative to scala-pact. The main feature gap I see at the moment is the inability to handle provider states when checking pacts. However, I also notice that pact-jvm has native support for scalatest providers

https://github.com/pact-foundation/pact-jvm/tree/master/provider/scalatest

and that it seems to offer pretty rich support for modeling provider states so it might be worth linking to them.

**Comment by jbwheatley** [comment]
Hi @caoilte. Version 0.0.10 adds initial support for handling provider state. See here for how to use it: https://github.com/jbwheatley/pact4s#provider-state

**Comment by caoilte** [comment]
@jbwheatley nice one. Just got that working. I don't like it, but I can see it's because you're mainly just shadowing the JVM implementation.
