### ISSUE TITLE
SimpleTimeLimiter exception

### ISSUE THREAD

**Issue by chameleon82** [jbwheatley/pact4s#278]
In some projects I got exception when use `pactVerify` method:

```console
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.<init>(Ljava/util/concurrent/ExecutorService;)V from class pact4s.TimeLimiter$
```
version: 0.5.0

**Comment by jbwheatley** [comment]
@chameleon82 this is most likely due to library incompatibility - pact-jvm brings in `com.google.guava:failureaccess:1.0.1` for `SimpleTimeLimiter` - is your project also depending on a different version of that library?

**Comment by jbwheatley** [comment]
I'm replacing the time limiter with a native scala one, so the next version of pact4s shouldn't have this issue

**Comment by jbwheatley** [comment]
@chameleon82 could you try 0.5.1 and see if the issue is fixed

**Comment by chameleon82** [comment]
@jbwheatley Thank you. It works now.
