### ISSUE TITLE
Improve state change error message

### ISSUE THREAD

**Issue by jbwheatley** [jbwheatley/pact4s#296]
if the state change function doesn't have a matching case, then the output message will just be something like: `State change callback failed with an exception - State Change Request Failed - 400 Bad Request
`.

It would be much better if we provided more context on why the callback failed, e.g. "expected state "bla bla", received state "blo blo""

**Comment by gaeljw** [comment]
Correct me if I'm wrong but providing a good error message for "non matching case" will be hard as it's sometimes expected to not having a matching case (like for pending pacts which aims to be the enabled by default).

That being said, for a matching case that throws an error, a nicer error message could be indeed helpful but I feel it already contains what user need to know. It's just a bit hidden in the output IMHO.
