### ISSUE TITLE
Using Generators

### ISSUE THREAD

**Issue by mone** [jbwheatley/pact4s#310]
Hello! 
I'm not sure if I'm being dense but I can't figure out how to use `generators` with `pact4s` on the `Provider` side of things
Forgive me if I don't use the correct lexicon, I'm super new to pact and inheriting incomplete code  

My `Consumer` generates a pact that contains something like this:
```"request": {
        "generators": {
          "header": {
            "Authorization": {
              "dataType": "STRING",
              "expression": "Bearer ${bearerToken}",
              "type": "ProviderState"
            }
          }
        },
        "headers": {
          "Authorization": "Bearer super-secure"
        },
        "method": "GET",
        "path": "/whatever"
      },
```

If I understand this correctly, this allows the `Provider` code to inject its `bearerToken` to be then used as a param during the contract test, so I expected to be able to return these generated params back in the `withStateChangeFunction` function but that function is instead a `ProviderState => Unit` so I can't return anything.

I did some changes locally to `pact4s` itself and made that function into a `ProviderState => ProviderState` so I was able to do the injecting I required, but I wanted to engage here first to understand if what I'm doing makes sense, before sending a PR over

**Comment by jbwheatley** [comment]
Hey @mone. 

I think in this situation you want to use request filtering on the provider. 

On `ProviderInfoBuilder` you can provide a request filter with `.withRequestFiltering` as we do here: https://github.com/jbwheatley/pact4s/blob/212b2eccede0abb15709bf554426b989d7aca8d6/shared/src/test/scala/pact4s/MockProviderServer.scala#L128

This can be used in the provider suite to inject a working auth token before the requests are run against your test server.

**Comment by mone** [comment]
Thanks for getting back to me!
I'll give it a try, thanks again!
