### ISSUE TITLE
Does pact4s support connection to Pactflow broker on the provider side?

### ISSUE THREAD

**Issue by celia-tray** [jbwheatley/pact4s#331]
Hi,

I'm currently stuck implementing the verification on the provider side against the pacts published by the consumer on the pactflow broker.
In my code, I've set up the following:

`val provider: ProviderInfoBuilder = ProviderInfoBuilder(
    "PROVIDER_SERVICE_NAME",
    PactSource.PactBrokerWithSelectors(
      "https://tray.pactflow.io",
    )
      .withAuth(TokenAuth(Properties.envOrElse("PACTFLOW_READ_WRITE_TOKEN", "")))
      .withConsumerVersionSelectors(ConsumerVersionSelectors()
        .branch(Properties.envOrElse("CONSUMER_BRANCH", "dev"), Some("CONSUMER_SERVICE_NAME"), None)
      )
  ).withHost("localhost")
    .withPort(port)
    .withRequestFiltering {...etc`

The tests run locally against a file, however when I change it to pactflow and run the tests on the pipeline I'm getting this error:
`munit.FailException: /home/runner/work/api-service/api-service/src/pact/scala/../pact/provider/TEST_FILE.scala:59 Call to fetch pacts from Pact Broker failed with an exception
58:  test("Verify cluster service pacts successfully") {
59:    verifyPacts(
60:      publishVerificationResults = Some(PublishVerificationResults("CONSUMER_ID_FROM_PACTFLOW")),`

(Some names are edited for company privacy)

With the tests failing in the pipeline but no errors showing on pactflow, it seems like the verification isn't reaching pactflow at all. We're currently stuck in our implementation, so I'd like to know whether there's something missing from the code, or whether it is expected for pact4s not to connect to pactflow.

Thank you for your time

**Comment by jbwheatley** [comment]
hi @celia-tray - I'm just releasing v0.7.0 which gives more information on the exceptions returned by pact-jvm. This should help you diagnose the issue. It should be out this afternoon

**Comment by celia-tray** [comment]
Hi @jbwheatley thank you for your response, sadly when I updated the version the error remains the same

**Comment by jbwheatley** [comment]
does the error string not now contain a cause? the failure should be getting raised here https://github.com/jbwheatley/pact4s/blob/11cafc8c562cf3d7d207aa7f511d99c0aca7995b/shared/src/main/scala/pact4s/PactVerifyResources.scala

**Comment by celia-tray** [comment]
Hi @jbwheatley sorry I think it took some time to sync, the error is now more informative: `munit.FailException: /home/runner/work/api-service/api-service/src/pact/scala/io/tray/pact/provider/ApiServiceProviderVerificationTest.scala:59 Call to fetch pacts from Pact Broker failed with an exception - cause: No HAL document found at path`
Thank you for your help!

**Comment by celia-tray** [comment]
This was really helpful to move the issue forward and fix it @jbwheatley thank you so much, closing the issue now
