### ISSUE TITLE
support for `au.com.dius.pact.consumer.dsl.PactBuilder`

### ISSUE THREAD

**Issue by jbwheatley** [jbwheatley/pact4s#337]
`au.com.dius.pact.consumer.dsl.PactBuilder` is required to construct V4 pacts, and the constructors we currently support (`au.com.dius.pact.consumer.ConsumerPactBuilder` and `au.com.dius.pact.consumer.MessagePactBuilder`) are now considered legacy. 

We should add extension methods to aid in the creation of pacts using this new dsl, similar to what we do in https://github.com/jbwheatley/pact4s/tree/main/shared/src/main/scala/pact4s/syntax

**Comment by ichengchang** [comment]
Great job on [pact4s](https://github.com/jbwheatley/pact4s)! My team has just started writing pacts using the scala test framework and I'm wondering if the V4 spec is currently supported.

We tried specifying V4 in the consumer pact builder as follows
ConsumerPactBuilder
  .consumer("consumer")
  .pactSpecVersion(PactSpecVersion.V4)
  .hasPactWith("provider")
but we are getting the following error in sbt test

au.com.dius.pact.core.support.V4PactFeaturesException: Pact specification V4 features can not be used with version V3 - Ignore Order matchers can only be used with Pact specification versions >= V4, Ignore Order matchers can only be used with Pact specification versions >= V4

For anyone following this issue, here's Jack's recommendation to construct V4 pacts. 

```
It looks like V4 support requires you to use au.com.dius.pact.consumer.dsl.PactBuilder rather than au.com.dius.pact.consumer.ConsumerPactBuilder to construct V4 pacts. 
This interface is a little clunky to use as we haven't added any syntactic sugar for this class yet, but that will be coming! 
```

**Comment by gaeljw** [comment]
Is this issue still relevant? I wanted to work on it but from what I see on the main branch `au.com.dius.pact.consumer.dsl.PactBuilder` is used, right?
