### ISSUE TITLE
update readme.md: Is Scala3 still blocked?

### ISSUE THREAD

**Issue by domdorn** [jbwheatley/pact4s#343]
The readme mentions 
> 1 support for scala 3 is currently blocked by https://github.com/lampepfl/dotty/issues/12086, as pact-jvm is written in kotlin 

is this still the case? The dotty issue is marked as fixed. 

I'm asking cause a team member currently doing his bachelor-thesis introduced pact4s to our project and I just figured out now that it pulls a huge amount of dependencies into the project and if it additionally would also block us from upgrading to scala 3, that would be an even bigger problem in the future.

Thanks!

**Comment by jbwheatley** [comment]
thanks for pointing this out, will update the readme as scala 3 is supported.

**Comment by domdorn** [comment]
thx!
