### ISSUE TITLE
Update default for PactSpecVersion to V4

### ISSUE THREAD

**Issue by solarmosaic-kflorence** [jbwheatley/pact4s#35]
https://github.com/jbwheatley/pact4s/blob/549bc3e76d3e377862438f6f748075499cc39f7d/shared/src/main/scala/pact4s/MessagePactForgerResources.scala#L23

**Comment by jbwheatley** [comment]
not sure I agree with having the default be the version of the pact spec that is still a WIP

**Comment by solarmosaic-kflorence** [comment]
It is still WIP, but it does address some bugs and outstanding features that are not available in V3. I'm generally a fan of being on the latest unless an issue forces you to downgrade, especially since this project is constantly getting updates from `pact-jvm` -- but it's also not a big deal since I can set it myself manually.
