### ISSUE TITLE
Add CI workflow to PR and merge

### ISSUE THREAD

**Issue by kflorence** [jbwheatley/pact4s#36]
We should run CI checks against PRs, and again during the release process prior to publish. Probably we can just use github actions workflows for this, perhaps with https://github.com/djspiewak/sbt-github-actions

**Comment by jbwheatley** [comment]
I've tried adding it, but the build gets about half way through then hangs indefinitely 😿 its completely unclear what the issue could be related to

**Comment by kflorence** [comment]
@jbwheatley you should create a PR so I can help :D

**Comment by jbwheatley** [comment]
it just gets part way through the first test run then hangs, and doesn't give any meaningful output https://github.com/jbwheatley/pact4s/actions/runs/1125350523

**Comment by jbwheatley** [comment]
Thought it could be some sort of file deadlock so tried turning off parallel execution, but doesn't seem that is it. Memory issue? No idea🤷‍♂️

**Comment by kflorence** [comment]
Well, the build has gotten pretty complicated, but it's strange that it just hangs. Github has been having issues the past few days, unsure if related. It seems to have gotten stuck on the Weaver tests, is it possible there is something waiting infinitely for a future to complete?

**Comment by kflorence** [comment]
@jbwheatley seems like this one is implemented now? I will close, you can re-open if you disagree.

**Comment by jbwheatley** [comment]
Yeah, its mostly done, except the build in GHA always hangs on the weaver tests. I need to follow up with that, but fine to close this for now
