### ISSUE TITLE
State Change Request Failed - localhost:64646 failed to respond

### ISSUE THREAD

**Issue by KostiantynVoznesenskyi** [jbwheatley/pact4s#375]
Hello folks! I'm new to pact4s and contract testing in general and I've run into an issue: 
`State Change Request Failed - localhost:64646 failed to respond`
My understanding after debugging is following:
StateManagementFunction is augmented with endpoint information by default, which is then used to manipulate state.
StateManagement is a sealed trait with two descendants:
- ProviderUrl 
- StateManagementFunction

My understanding from examples was that one would only need one of those to manage state of provider either by a function or via HTTP endpoint.  But latest version still tries to access given endpoint after execution of a partial function provided via `withStateChangeFunction`. Which doesn't make much sense.
 Please clarify.

**Comment by jbwheatley** [comment]
Hi,

Using the state management function does spin up a server on `localhost:64646`,[ I've expanded the readme to cover this in more detail. ](https://github.com/jbwheatley/pact4s#provider-state)

Could you post a reproducible example of your problem? It sounds like there is some issue with this server but I wouldn't have enough information to go off

**Comment by KostiantynVoznesenskyi** [comment]
Maybe it didn't start for some reason. Could you please point me where it is started ?
Also could you please elaborate on why we need this server when we have state change function ?
I don't really have an extended stack trace myself.

**Comment by jbwheatley** [comment]
The server is created here https://github.com/jbwheatley/pact4s/blob/620c708d9f607c83dafaba1a3a1dbe15500135a3/shared/src/main/scala/pact4s/StateChanger.scala#L38

As mentioned in the readme section I linked, the state-change function requires a http server to receive the state-change requests generated by the underlying pact-jvm library. The function interface pact4s provides is simply a shortcut we have added for users to manage state without also having to manage their own state-change endpoint or server. 

 If something in that readme section isn't clear, could you please let me know. 

It would be useful if you could let me know the version of pact4s you are using, and if this issue persists on a previous version.

Could you also post the full console output of that error, it would be helpful if there is any additional information with the error message. 

We do have tests covering this state-change functionality, so it is possible there is something wrong with your particular usage - if you can share any of that code (with any sensitive information removed, of course), that would help narrow down the problem

**Comment by KostiantynVoznesenskyi** [comment]
I'm using "0.8.0" version of pact4s.
Readme is fine, thank you.
I now see that the issue is that pact-jvm doesn't offer this nice functional interface and expects users to spin up http server.

**Comment by KostiantynVoznesenskyi** [comment]
The server is actually up and executing get request on http://localhost:64646/pact4s-state-change returns `{}`

**Comment by KostiantynVoznesenskyi** [comment]
The error "failed to respond" is actually thrown here https://github.com/apache/httpcomponents-client/blob/94017237b2046574267f46bf6f441bc560378b58/httpclient5/src/main/java/org/apache/hc/client5/http/impl/classic/HttpRequestRetryExec.java 
I bet it's due to timeout.

**Comment by KostiantynVoznesenskyi** [comment]
My state change functions are trivial, they are not causing it.
I understand that integration issues are hard.
I would consider using ByteBuddy to change implementation of StateChange in PactJVM so that it will call StateChangeFunction provided in PactVerification. Instead of all this HTTP ping-pong.

**Comment by jbwheatley** [comment]
Editing the runtime behaviour of pact-jvm is beyond the scope of this library and not something I want to maintain. If you'd like a state-change function to be available natively in pact-jvm I suggest opening an issue there! 

I will probably close this issue if you're unable to put together a reproducible example of this, as I don't really have anything to go off of to help you.

**Comment by KostiantynVoznesenskyi** [comment]
It doesn't throw this exception with an empty StateChangeFunction, doesn't throw it If StateChangeFunction throws.
I tried to provoke a timeout and it didn't throw this exact exception either. So I think it's something specific to my state change actions.
