### ISSUE TITLE
LambdaDsl in Java 8

### ISSUE THREAD

**Issue by tanyagorn** [jbwheatley/pact4s#486]
This is my project dependency 
"io.github.jbwheatley" %% "pact4s-scalatest" % "0.10.0-java8"

Somehow I cannot import au.com.dius.pact.consumer.dsl.LambdaDsl.* into my project. Is it because LambdaDsl doesn't support in Java 8?

Assume that it doesn't support, that mean the only way I can write Pact is using PactDslJsonBody. Is there any alternative method less painful than this? upgrading project jdk version is not an option here either.

**Comment by gaeljw** [comment]
I just wrote a compatibility matrix in https://github.com/jbwheatley/pact4s/pull/522 that should clarify the situation.

Pact4s Java8 versions are using Pact JVM 4.1.x which doesn't provide `LambdaDsl`.

JDK8 is soon 10 years old, I would strongly encourage to move to at very least Java 11 or better Java 17. Most popular frameworks and libraries are dropping support for JDK8.
