### ISSUE TITLE
Provider tags must be provided if pending pacts are enabled

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#520]
When using the pending pact feature in provider tests, with something like the following:

```
PactSource
    .PactBrokerWithSelectors(PactBrokerUrl)
    .withConsumerVersionSelectors(ConsumerVersionSelectors.mainBranch)
    .withPendingPacts(true)
```

We get the error _Provider tags must be provided if pending pacts are enabled_.

This can be solved easily by providing tags directly or by using `.withPendingPactsEnabled(tags)` which explicitly asks for tags.

But, the concept of tags in Pact is deprecated for some time already (in favour of branches especially) and I don't find any reason in the [documentation](https://docs.pact.io/pact_broker/advanced_topics/pending_pacts) that states tags must be set for pending pacts to work.

Should we remove this check and allow usage of the "pending pacts" feature without tags?

I'll be happy to provide a PR for this.

**Comment by gaeljw** [comment]
For reference the check is done in https://github.com/jbwheatley/pact4s/blob/17f48624d8c88904315e2e36fd242522cd596708/models/src/main/scala/pact4s/provider/PactSource.scala#L196

**Comment by mefellows** [comment]
Pending Pacts work for branches, yes. You’re right, that restriction should be lifted to support provider branch as an alternative constraint.
