### ISSUE TITLE
Add ScalaJS / Scala Native support

### ISSUE THREAD

**Issue by alexcardell** [jbwheatley/pact4s#533]
A big ask, I'm sure. Most of the test frameworks support ScalaJS and Scala Native, and there are Pact libraries for JS and Rust / C++. Could we fully abstract pact4s by removing direct references to JVM types in the interfaces, and then delegate to the relevant library?

**Comment by jbwheatley** [comment]
This library is coupled very tightly to pact-jvm, so I can only think that this would be a massive undertaking that goes far beyond the scope of what pact4s aims to do. I also suspect the user-base would be diminishingly small, so I don't think we can reasonably help with this, sorry
