### ISSUE TITLE
Is the library still maintained?

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#549]
I see several PRs open for few months without any feedback. 

What's the status of the project?

Would you accept additional maintainers?

**Comment by jbwheatley** [comment]
Hi @gaeljw . funny that I looked at the repo the same day you asked. I unfortunately haven't worked at a company using pact for 2 years now, so on top of not having time for opensource dev I also have no motivating factor to maintain this project myself. Happy to add you as a maintainer

**Comment by gaeljw** [comment]
I'd be happy to help as much as I can, at least get the open PRs merged :)

**Comment by jbwheatley** [comment]
thanks a lot. Sorry I haven't been maintaining this project for a while :(

**Comment by gaeljw** [comment]
@jbwheatley no worries, that's how OSS works, we dedicate some personal time as long as we can/want and nobody can blame you for having other priorities ;)
