### ISSUE TITLE
Drop support for Java 8

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#551]
**💡 If you are still using the Java 8 artifacts and believe it should still be maintained, please comment in this issue.**

---

I suggest that we drop support for Java 8, that is stop publishing `-java8` suffixed artifacts.

Pact JVM hasn't released any new version on their Java 8 compatible branch (4.1.x) for more than a year now.

This will simplify maintenance of this project and also encourage everyone to move on with recent Java versions.

We'll notify this proposition in the next release notes (0.11.0), letting users a bit of time to raise their hands if they have strong reasons to keep using a Java 8 compatible version.

**Comment by jbwheatley** [comment]
I'd also suggest dropping weaver support for similar reasons, I don't think its widely used. I'll check the download stats

**Comment by jbwheatley** [comment]
I'm going to turn off scala steward updates for java8 and close the open prs

**Comment by jbwheatley** [comment]
i couldn't find the download stats - seems like sonatype has moved a load of stuff around and i can't find shit anymore
