### ISSUE TITLE
Drop support for Scala 2.12

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#597]
Some of our dependencies (http4s for instance) are not published anymore for Scala 2.12.

While maintaining pact4s for Scala 2.12 is not especially painful, we'll have to do it at some point to keep using latest versions of our dependencies.

See:
- #595 
- #596

**Comment by jbwheatley** [comment]
as we only use http4s for the example module I wouldn't want to drop support just for that. It was a mistake to use a milestone version of http4s in the first place and I'll probably change it to use the stable version with 2.12 support

**Comment by gaeljw** [comment]
> as we only use http4s for the example module I wouldn't want to drop support just for that. It was a mistake to use a milestone version of http4s in the first place and I'll probably change it to use the stable version with 2.12 support

Oh right, I was thinking http4s was used in the core of pact4s but looks like it's only for tests.

We can wait for more reasons to drop Scala 2.12 then, no pressure :)
