### ISSUE TITLE
Release process is broken

### ISSUE THREAD

**Issue by gaeljw** [jbwheatley/pact4s#665]
See the latest release attempt (0.13.1): https://github.com/jbwheatley/pact4s/actions/runs/9640757836/job/26585102930

> ```
> 2024-06-24 06:40:35.027Z  info [SonatypeClient] Uploading bundle /home/runner/work/pact4s/pact4s/target/sonatype-staging/0.13.1 to https://s01.oss.sonatype.org/service/local/staging/deployByRepositoryId/iogithub***-1056/  - (SonatypeClient.scala:296)
> 2024-06-24 06:40:35.259Z error [Sonatype] 
> java.io.IOException: Failure:java.util.concurrent.ExecutionException: java.io.IOException: Unexpected server response: 401 Content access is protected by token
> 	at org.sonatype.spice.zapper.internal.transport.AbstractChargerClient.doUpload(AbstractChargerClient.java:65)
> ```

I believe this is related to recent changes with [Sonatype requiring the usage of a token](https://central.sonatype.org/news/20240617_migration_of_accounts/) instead of username/password. @jbwheatley any chance you could have a look at this?

See also https://central.sonatype.org/publish/generate-token/

**Comment by jbwheatley** [comment]
done

**Comment by gaeljw** [comment]
Thanks :)
